title: "Scott Markley"
author: "Scott Markley"
description: "2021"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_social: true           # show social media links
show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "ProjectLinks.md", title: "Projects"}
  - {url: "/cv/CV_oct2021.pdf", title: "CV"}
  - {file: "ProjectsOld.md", title: "TEST"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/snmarkley1"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/snmarkley"}
  - {title: Google Scholar, icon: graduation-cap, url: "https://scholar.google.com/citations?user=onwbEAoAAAAJ&hl=en&oi=ao"}
  - {title: Mail, icon: envelope, url: "mailto:scott.markley@uga.edu"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
